server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/card_creator_directory
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

application:
  name: card-creator

logging:
  level:
    root: debug